/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalystRouteImport } from './routes/analyst'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AwardRouteImport } from './routes/award'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as QuestionnaireRouteImport } from './routes/questionnaire'
import { Route as ResponsesRouteImport } from './routes/responses'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as RfxRouteImport } from './routes/rfx'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as VendorsRouteImport } from './routes/vendors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystRoute = AnalystRouteImport.update({
  id: '/analyst',
  path: '/analyst',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardRoute = AwardRouteImport.update({
  id: '/award',
  path: '/award',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireRoute = QuestionnaireRouteImport.update({
  id: '/questionnaire',
  path: '/questionnaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsesRoute = ResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const RfxRoute = RfxRouteImport.update({
  id: '/rfx',
  path: '/rfx',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRoute
  '/audit': typeof AuditRoute
  '/award': typeof AwardRoute
  '/intelligence': typeof IntelligenceRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/responses': typeof ResponsesRoute
  '/review': typeof ReviewRoute
  '/rfx': typeof RfxRoute
  '/scenarios': typeof ScenariosRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRoute
  '/audit': typeof AuditRoute
  '/award': typeof AwardRoute
  '/intelligence': typeof IntelligenceRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/responses': typeof ResponsesRoute
  '/review': typeof ReviewRoute
  '/rfx': typeof RfxRoute
  '/scenarios': typeof ScenariosRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRoute
  '/audit': typeof AuditRoute
  '/award': typeof AwardRoute
  '/intelligence': typeof IntelligenceRoute
  '/questionnaire': typeof QuestionnaireRoute
  '/responses': typeof ResponsesRoute
  '/review': typeof ReviewRoute
  '/rfx': typeof RfxRoute
  '/scenarios': typeof ScenariosRoute
  '/vendors': typeof VendorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyst'
    | '/audit'
    | '/award'
    | '/intelligence'
    | '/questionnaire'
    | '/responses'
    | '/review'
    | '/rfx'
    | '/scenarios'
    | '/vendors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyst'
    | '/audit'
    | '/award'
    | '/intelligence'
    | '/questionnaire'
    | '/responses'
    | '/review'
    | '/rfx'
    | '/scenarios'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/analyst'
    | '/audit'
    | '/award'
    | '/intelligence'
    | '/questionnaire'
    | '/responses'
    | '/review'
    | '/rfx'
    | '/scenarios'
    | '/vendors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalystRoute: typeof AnalystRoute
  AuditRoute: typeof AuditRoute
  AwardRoute: typeof AwardRoute
  IntelligenceRoute: typeof IntelligenceRoute
  QuestionnaireRoute: typeof QuestionnaireRoute
  ResponsesRoute: typeof ResponsesRoute
  ReviewRoute: typeof ReviewRoute
  RfxRoute: typeof RfxRoute
  ScenariosRoute: typeof ScenariosRoute
  VendorsRoute: typeof VendorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst': {
      id: '/analyst'
      path: '/analyst'
      fullPath: '/analyst'
      preLoaderRoute: typeof AnalystRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/award': {
      id: '/award'
      path: '/award'
      fullPath: '/award'
      preLoaderRoute: typeof AwardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire': {
      id: '/questionnaire'
      path: '/questionnaire'
      fullPath: '/questionnaire'
      preLoaderRoute: typeof QuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responses': {
      id: '/responses'
      path: '/responses'
      fullPath: '/responses'
      preLoaderRoute: typeof ResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfx': {
      id: '/rfx'
      path: '/rfx'
      fullPath: '/rfx'
      preLoaderRoute: typeof RfxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalystRoute: AnalystRoute,
  AuditRoute: AuditRoute,
  AwardRoute: AwardRoute,
  IntelligenceRoute: IntelligenceRoute,
  QuestionnaireRoute: QuestionnaireRoute,
  ResponsesRoute: ResponsesRoute,
  ReviewRoute: ReviewRoute,
  RfxRoute: RfxRoute,
  ScenariosRoute: ScenariosRoute,
  VendorsRoute: VendorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
